<a href="https://colab.research.google.com/github/CE334/CE334_230515_Kalavatala_Sowmya/blob/main/CE334_Sowmya_kalavatala_230515_lab0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# NumPy is used for numerical and matrix computations
import numpy as np

# Pandas is used for reading and handling CSV data
import pandas as pd


In [13]:
#1st question

# Creating a row vector manually
row_vec = np.array([1, 2, 3])

# Creating a column vector manually
col_vec = np.array([[1], [2], [3]])

print("Row Vector:", row_vec)
print("Column Vector:\n", col_vec)


Row Vector: [1 2 3]
Column Vector:
 [[1]
 [2]
 [3]]


In [15]:
# Taking input from user for row vector
row_input = list(map(float, input("Enter row vector elements: ").split()))
row_vec_input = np.array(row_input)

# Taking input from user for column vector
col_input = list(map(float, input("Enter column vector elements: ").split()))
col_vec_input = np.array(col_input).reshape(-1, 1)

print("Input Row Vector:", row_vec_input)
print("Input Column Vector:\n", col_vec_input)


Enter row vector elements: 11 22 33 44 
Enter column vector elements: 55 66 77 88 
Input Row Vector: [11. 22. 33. 44.]
Input Column Vector:
 [[55.]
 [66.]
 [77.]
 [88.]]


In [35]:
#2nd question
import numpy as np

# Creating a random 5x5 non-singular matrix
# We will try to create a random matrix until it's non-singular
# (i.e., its determinant is not zero).
# For large random matrices, the probability of being singular is very low.
a = np.random.rand(5, 5)
while np.linalg.det(a) == 0:
    a = np.random.rand(5, 5)

print("Matrix a (non-singular):\n", a)

Matrix a (non-singular):
 [[0.934256   0.07797102 0.292095   0.26361848 0.14628399]
 [0.82810189 0.7281222  0.39185036 0.62852942 0.72583099]
 [0.34082883 0.90624506 0.58182718 0.20199025 0.05977079]
 [0.99838387 0.17669323 0.97652768 0.95393324 0.27098432]
 [0.08077097 0.38269525 0.57350527 0.13989554 0.63292455]]


In [19]:
# Taking 25 elements from user to form a 5x5 matrix
print("Enter 25 elements for 5x5 matrix:")
elements = list(map(float, input().split()))
a_input = np.array(elements).reshape(5, 5)

print("Input Matrix:\n", a_input)


Enter 25 elements for 5x5 matrix:
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
Input Matrix:
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


In [21]:
#3rd question
# Indexing starts from 0, so 3rd row has index 2
third_row = a[2, :]
print("3rd Row of matrix a:", third_row)


3rd Row of matrix a: [3 4 5 6 7]


In [22]:
#4rth question
# 4th column has index 3
fourth_column = a[:, 3]
print("4th Column of matrix a:", fourth_column)


4th Column of matrix a: [4 5 6 7 8]


In [23]:

#5th question
row_sorted = np.sort(a, axis=1)
print("Row-wise sorted matrix:\n", row_sorted)


Row-wise sorted matrix:
 [[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]


In [25]:
column_sorted = np.sort(a, axis=0)
print("Column-wise sorted matrix:\n", column_sorted)


Column-wise sorted matrix:
 [[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]


In [26]:
#5th question
# Copying matrix a into b
b = a.copy()

# If element is greater than 2, multiply it by 10
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if a[i, j] > 2:
            b[i, j] = a[i, j] * 10

print("Matrix b after condition:\n", b)


Matrix b after condition:
 [[ 1  2 30 40 50]
 [ 2 30 40 50 60]
 [30 40 50 60 70]
 [40 50 60 70 80]
 [50 60 70 80 90]]


In [27]:
#7th question
add_result = a + b
print("Addition of a and b:\n", add_result)


Addition of a and b:
 [[ 2  4 33 44 55]
 [ 4 33 44 55 66]
 [33 44 55 66 77]
 [44 55 66 77 88]
 [55 66 77 88 99]]


In [28]:
#8th question
sub_result = a - b
print("Subtraction of b from a:\n", sub_result)


Subtraction of b from a:
 [[  0   0 -27 -36 -45]
 [  0 -27 -36 -45 -54]
 [-27 -36 -45 -54 -63]
 [-36 -45 -54 -63 -72]
 [-45 -54 -63 -72 -81]]


In [29]:
#9th question
elementwise_mult = a * b
print("Element-wise multiplication:\n", elementwise_mult)


Element-wise multiplication:
 [[  1   4  90 160 250]
 [  4  90 160 250 360]
 [ 90 160 250 360 490]
 [160 250 360 490 640]
 [250 360 490 640 810]]


In [30]:
matrix_mult = np.dot(a, b)
print("Matrix multiplication:\n", matrix_mult)


Matrix multiplication:
 [[ 505  682  850 1000 1150]
 [ 628  864 1100 1300 1500]
 [ 751 1046 1350 1600 1850]
 [ 874 1228 1600 1900 2200]
 [ 997 1410 1850 2200 2550]]


In [31]:
#10th question
a_divided = a / 18
b_divided = b / 18

print("Matrix a divided by 18:\n", a_divided)
print("Matrix b divided by 18:\n", b_divided)


Matrix a divided by 18:
 [[0.05555556 0.11111111 0.16666667 0.22222222 0.27777778]
 [0.11111111 0.16666667 0.22222222 0.27777778 0.33333333]
 [0.16666667 0.22222222 0.27777778 0.33333333 0.38888889]
 [0.22222222 0.27777778 0.33333333 0.38888889 0.44444444]
 [0.27777778 0.33333333 0.38888889 0.44444444 0.5       ]]
Matrix b divided by 18:
 [[0.05555556 0.11111111 1.66666667 2.22222222 2.77777778]
 [0.11111111 1.66666667 2.22222222 2.77777778 3.33333333]
 [1.66666667 2.22222222 2.77777778 3.33333333 3.88888889]
 [2.22222222 2.77777778 3.33333333 3.88888889 4.44444444]
 [2.77777778 3.33333333 3.88888889 4.44444444 5.        ]]


In [38]:
#11th question
# Inverse of matrix a
print("Inverse of matrix a:\n", np.linalg.inv(a))

# Rank of matrix a
print("Rank of matrix a:", np.linalg.matrix_rank(a))

# Condition number of matrix a
print("Condition number of matrix a:", np.linalg.cond(a))

# Singular Value Decomposition of matrix a
U, S, Vt = np.linalg.svd(a)
print("Singular values of matrix a:\n", S)

# Norms of matrices
print("Norm of matrix a:", np.linalg.norm(a))
print("Norm of matrix b:", np.linalg.norm(b))

Inverse of matrix a:
 [[ 1.50935616 -0.0462888   0.03909346 -0.37448559 -0.13912198]
 [-0.38476036  0.57063043  0.96089246 -0.40212899 -0.48403815]
 [ 0.36962709 -1.30976145  0.4324962   0.49881817  1.16218022]
 [-1.92382335  1.11259125 -0.40956598  1.12016216 -1.27218159]
 [ 0.13032363  0.60176174 -0.88735537 -0.40864291  1.11850958]]
Rank of matrix a: 5
Condition number of matrix a: 8.774498097116695
Singular values of matrix a:
 [2.61908474 0.95657066 0.58803313 0.56953315 0.29848827]
Norm of matrix a: 2.92128028424565
Norm of matrix b: 267.5985799663369


In [39]:
#12th question
# Norm of column vector
print("Norm of column vector:", np.linalg.norm(col_vec))

# Inner product of column vector
inner_product = np.dot(col_vec.T, col_vec)
print("Inner product:\n", inner_product)

# Outer product of column vector
outer_product = np.outer(col_vec, col_vec)
print("Outer product:\n", outer_product)


Norm of column vector: 3.7416573867739413
Inner product:
 [[14]]
Outer product:
 [[1 2 3]
 [2 4 6]
 [3 6 9]]


In [45]:
#13th question
def derivative(f, a, method='central', h=0.01):
    """
    This function computes the numerical derivative of f(x)
    at point a using forward, backward or central difference.
    """
    if method == 'forward':
        return (f(a + h) - f(a)) / h
    elif method == 'backward':
        return (f(a) - f(a - h)) / h
    elif method == 'central':
        return (f(a + h) - f(a - h)) / (2 * h)


In [47]:
print("Derivative of e^x at x=0.5:", derivative(np.exp, 0.5))
print("Derivative of cos(x) at x=0.5:", derivative(np.cos, 0.5))


Derivative of e^x at x=0.5: 1.648748749525375
Derivative of cos(x) at x=0.5: -0.4794175482185081


In [46]:
#14th question
# Reading AWS CSV file into a DataFrame
aws_data = pd.read_csv("AWS_Data.csv")

# Display first five rows
print(aws_data.head())


                  created_at  entry_id  Soil Temperature  Soil Moisture  \
0  2022-12-14T14:19:11+05:30     10830             21.06            817   
1  2022-12-14T14:20:13+05:30     10831             21.06            817   
2  2022-12-14T14:21:15+05:30     10832             21.06            817   
3  2022-12-14T14:22:18+05:30     10833             21.06            817   
4  2022-12-14T14:23:20+05:30     10834             21.06            817   

   Wind Speed  Rainfall  Temperature  Humidity  Pressure  Battery Voltage  
0         0.0      0.25        25.38     45.09      1.94             4.14  
1         0.0      0.25        25.27     46.52      1.94             4.14  
2         0.0      0.25        25.34     45.79      1.94             4.14  
3         0.0      0.25        25.13     44.91      1.94             4.15  
4         0.0      0.25        24.95     45.12      1.94             4.15  
